"""Agent planning and reasoning trace structures."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class PlanStep:
    """A single action/tool step planned or executed by the agent."""

    tool_name: str
    reasoning: str
    inputs: dict[str, Any] = field(default_factory=dict)
    output_summary: str = ""
    latency_ms: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "tool_name": self.tool_name,
            "reasoning": self.reasoning,
            "inputs": self.inputs,
            "output_summary": self.output_summary,
            "latency_ms": self.latency_ms,
        }


@dataclass
class ReasoningTrace:
    """Full reasoning trace displayed in the Developer Dashboard."""

    need_retrieval: bool = True
    need_query_rewrite: bool = False
    need_metadata_filter: bool = False
    need_multi_hop: bool = False
    need_hyde: bool = False
    enough_evidence: bool = False
    steps: list[PlanStep] = field(default_factory=list)
    iterations_taken: int = 1

    def to_dict(self) -> dict[str, Any]:
        return {
            "need_retrieval": self.need_retrieval,
            "need_query_rewrite": self.need_query_rewrite,
            "need_metadata_filter": self.need_metadata_filter,
            "need_multi_hop": self.need_multi_hop,
            "need_hyde": self.need_hyde,
            "enough_evidence": self.enough_evidence,
            "steps": [s.to_dict() for s in self.steps],
            "iterations_taken": self.iterations_taken,
        }


@dataclass
class AgentPlan:
    """Plan generated by AgentPlanner."""

    trace: ReasoningTrace
    initial_steps: list[PlanStep]


class AgentPlanner:
    """Planner that analyzes user query and context to construct a structured reasoning trace."""

    def analyze(
        self,
        query: str,
        rewritten_query: str | None = None,
        metadata_filters: dict[str, Any] | None = None,
        hyde_used: bool = False,
        multi_hop_enabled: bool = False,
    ) -> AgentPlan:
        need_rewrite = bool(rewritten_query and rewritten_query != query)
        need_meta = bool(metadata_filters and len(metadata_filters) > 0)
        need_multi = bool(
            multi_hop_enabled
            and ("compare" in query.lower() or "difference" in query.lower() or len(query.split()) > 20)
        )

        trace = ReasoningTrace(
            need_retrieval=True,
            need_query_rewrite=need_rewrite,
            need_metadata_filter=need_meta,
            need_multi_hop=need_multi,
            need_hyde=hyde_used,
            enough_evidence=False,
        )

        steps: list[PlanStep] = [
            PlanStep(
                tool_name="RetrieveTool",
                reasoning="Execute hybrid dense/sparse retrieval with strict canonical company filtering",
                inputs={"query": rewritten_query or query, "filters": metadata_filters or {}},
                latency_ms=12.5,
            )
        ]

        if need_multi:
            steps.append(
                PlanStep(
                    tool_name="DecomposeQueryTool",
                    reasoning="Query involves comparison/multi-part question; decomposing into targeted sub-queries",
                    inputs={"query": rewritten_query or query},
                    latency_ms=8.2,
                )
            )

        steps.append(
            PlanStep(
                tool_name="EvaluateEvidenceTool",
                reasoning="Verify retrieved candidates meet grounding threshold and cross-encoder entailment score",
                inputs={"candidate_count": 8},
                latency_ms=4.1,
            )
        )
        steps.append(
            PlanStep(
                tool_name="GenerateAnswerTool",
                reasoning="Synthesize comprehensive handbook-style response using context and summarized dialogue history",
                inputs={"max_output_tokens": 8192},
                latency_ms=0.0,
            )
        )

        trace.steps = steps
        return AgentPlan(trace=trace, initial_steps=steps)
